version: "3.9"
services: 
  dashboard:
    restart: always
    build: .
    container_name: dashboard
    expose:
      - 8080
    environment:
      - "VIRTUAL_HOST=dashboard.vmvisioprom,www.dashboard.vmvisioprom,dashboard.vmvisioprom.kristal.local,www.dashboard.vmvisioprom.kristal.local,vmvisioprom.kristal.local,www.vmvisioprom.kristal.local,vmvisioprom,www.vmvisioprom"
      - "VIRTUAL_PORT=8080"
