version: "3.9"
services: 
  dashboard:
    restart: always
    build: .
    container_name: dashboard
    ports:
      - 8080:8080
    expose:
      - 8080
    environment:
      - VIRTUAL_HOST=mcd,www.mcd,mcd.kristal.local,www.mcd.kristal.local,vmvisioprom.kristal.local,www.vmvisioprom.kristal.local,vmvisioprom,www.vmvisioprom"
      - VIRTUAL_PORT=8080
      - VIRTUAL_NETWORK=proxy-network
networks:
  default: 
    external: 
      name: proxy-network